issue_template:
   feature: .github/workflows/ISSUE_TEMPLATE/feature.md
   documentation: .github/workflows/ISSUE_TEMPLATE/documentation.md
   bug: .github/workflows/ISSUE_TEMPLATE/bug.md
   other: .github/workflows/ISSUE_TEMPLATE/other.md
